// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: users/users.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ACTIVE      UserStatus = 1
	UserStatus_USER_STATUS_DISABLED    UserStatus = 2
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ACTIVE",
		2: "USER_STATUS_DISABLED",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ACTIVE":      1,
		"USER_STATUS_DISABLED":    2,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_users_users_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_users_users_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{0}
}

type AttributeKey int32

const (
	AttributeKey_ATTRIBUTE_KEY_UNSPECIFIED AttributeKey = 0
)

// Enum value maps for AttributeKey.
var (
	AttributeKey_name = map[int32]string{
		0: "ATTRIBUTE_KEY_UNSPECIFIED",
	}
	AttributeKey_value = map[string]int32{
		"ATTRIBUTE_KEY_UNSPECIFIED": 0,
	}
)

func (x AttributeKey) Enum() *AttributeKey {
	p := new(AttributeKey)
	*p = x
	return p
}

func (x AttributeKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeKey) Descriptor() protoreflect.EnumDescriptor {
	return file_users_users_proto_enumTypes[1].Descriptor()
}

func (AttributeKey) Type() protoreflect.EnumType {
	return &file_users_users_proto_enumTypes[1]
}

func (x AttributeKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttributeKey.Descriptor instead.
func (AttributeKey) EnumDescriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{1}
}

type IdentityProviderType int32

const (
	IdentityProviderType_IDENTITY_PROVIDER_TYPE_UNSPECIFIED      IdentityProviderType = 0
	IdentityProviderType_IDENTITY_PROVIDER_TYPE_ACTIVE_DIRECTORY IdentityProviderType = 1
	IdentityProviderType_IDENTITY_PROVIDER_TYPE_LDAP             IdentityProviderType = 2
)

// Enum value maps for IdentityProviderType.
var (
	IdentityProviderType_name = map[int32]string{
		0: "IDENTITY_PROVIDER_TYPE_UNSPECIFIED",
		1: "IDENTITY_PROVIDER_TYPE_ACTIVE_DIRECTORY",
		2: "IDENTITY_PROVIDER_TYPE_LDAP",
	}
	IdentityProviderType_value = map[string]int32{
		"IDENTITY_PROVIDER_TYPE_UNSPECIFIED":      0,
		"IDENTITY_PROVIDER_TYPE_ACTIVE_DIRECTORY": 1,
		"IDENTITY_PROVIDER_TYPE_LDAP":             2,
	}
)

func (x IdentityProviderType) Enum() *IdentityProviderType {
	p := new(IdentityProviderType)
	*p = x
	return p
}

func (x IdentityProviderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityProviderType) Descriptor() protoreflect.EnumDescriptor {
	return file_users_users_proto_enumTypes[2].Descriptor()
}

func (IdentityProviderType) Type() protoreflect.EnumType {
	return &file_users_users_proto_enumTypes[2]
}

func (x IdentityProviderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityProviderType.Descriptor instead.
func (IdentityProviderType) EnumDescriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{2}
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncludePii    bool                   `protobuf:"varint,1,opt,name=include_pii,json=includePii,proto3" json:"include_pii,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_users_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{0}
}

func (x *ListUsersRequest) GetIncludePii() bool {
	if x != nil {
		return x.IncludePii
	}
	return false
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserHash      string                 `protobuf:"bytes,1,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	IncludePii    bool                   `protobuf:"varint,2,opt,name=include_pii,json=includePii,proto3" json:"include_pii,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_users_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserRequest) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

func (x *GetUserRequest) GetIncludePii() bool {
	if x != nil {
		return x.IncludePii
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserHash      string                 `protobuf:"bytes,1,opt,name=user_hash,json=userHash,proto3" json:"user_hash,omitempty"`
	UserPii       *UserPII               `protobuf:"bytes,2,opt,name=user_pii,json=userPii,proto3,oneof" json:"user_pii,omitempty"`
	Status        UserStatus             `protobuf:"varint,3,opt,name=status,proto3,enum=users.UserStatus" json:"status,omitempty"`
	IdpType       IdentityProviderType   `protobuf:"varint,4,opt,name=idp_type,json=idpType,proto3,enum=users.IdentityProviderType" json:"idp_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_users_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetUserHash() string {
	if x != nil {
		return x.UserHash
	}
	return ""
}

func (x *User) GetUserPii() *UserPII {
	if x != nil {
		return x.UserPii
	}
	return nil
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *User) GetIdpType() IdentityProviderType {
	if x != nil {
		return x.IdpType
	}
	return IdentityProviderType_IDENTITY_PROVIDER_TYPE_UNSPECIFIED
}

type UserPII struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      *string                `protobuf:"bytes,1,opt,name=username,proto3,oneof" json:"username,omitempty"`                          // sAMAccountName, login, etc.
	Email         *string                `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`                                // mail, userPrincipalName
	DisplayName   *string                `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"` // displayName, cn
	FirstName     *string                `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`       // givenName
	LastName      *string                `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`          // sn, surname
	Phone         *string                `protobuf:"bytes,6,opt,name=phone,proto3,oneof" json:"phone,omitempty"`                                // telephoneNumber, mobile
	Department    *string                `protobuf:"bytes,7,opt,name=department,proto3,oneof" json:"department,omitempty"`                      // department
	Title         *string                `protobuf:"bytes,8,opt,name=title,proto3,oneof" json:"title,omitempty"`                                // title
	ManagerId     *string                `protobuf:"bytes,9,opt,name=manager_id,json=managerId,proto3,oneof" json:"manager_id,omitempty"`       // manager (reference)
	EmployeeId    *string                `protobuf:"bytes,10,opt,name=employee_id,json=employeeId,proto3,oneof" json:"employee_id,omitempty"`   // employeeID, employeeNumber
	Location      *string                `protobuf:"bytes,11,opt,name=location,proto3,oneof" json:"location,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,20,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPII) Reset() {
	*x = UserPII{}
	mi := &file_users_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPII) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPII) ProtoMessage() {}

func (x *UserPII) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPII.ProtoReflect.Descriptor instead.
func (*UserPII) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{3}
}

func (x *UserPII) GetUsername() string {
	if x != nil && x.Username != nil {
		return *x.Username
	}
	return ""
}

func (x *UserPII) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UserPII) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UserPII) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UserPII) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UserPII) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UserPII) GetDepartment() string {
	if x != nil && x.Department != nil {
		return *x.Department
	}
	return ""
}

func (x *UserPII) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UserPII) GetManagerId() string {
	if x != nil && x.ManagerId != nil {
		return *x.ManagerId
	}
	return ""
}

func (x *UserPII) GetEmployeeId() string {
	if x != nil && x.EmployeeId != nil {
		return *x.EmployeeId
	}
	return ""
}

func (x *UserPII) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return ""
}

func (x *UserPII) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Attribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           AttributeKey           `protobuf:"varint,1,opt,name=key,proto3,enum=users.AttributeKey" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_users_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_users_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_users_users_proto_rawDescGZIP(), []int{4}
}

func (x *Attribute) GetKey() AttributeKey {
	if x != nil {
		return x.Key
	}
	return AttributeKey_ATTRIBUTE_KEY_UNSPECIFIED
}

func (x *Attribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_users_users_proto protoreflect.FileDescriptor

const file_users_users_proto_rawDesc = "" +
	"\n" +
	"\x11users/users.proto\x12\x05users\"3\n" +
	"\x10ListUsersRequest\x12\x1f\n" +
	"\vinclude_pii\x18\x01 \x01(\bR\n" +
	"includePii\"N\n" +
	"\x0eGetUserRequest\x12\x1b\n" +
	"\tuser_hash\x18\x01 \x01(\tR\buserHash\x12\x1f\n" +
	"\vinclude_pii\x18\x02 \x01(\bR\n" +
	"includePii\"\xc3\x01\n" +
	"\x04User\x12\x1b\n" +
	"\tuser_hash\x18\x01 \x01(\tR\buserHash\x12.\n" +
	"\buser_pii\x18\x02 \x01(\v2\x0e.users.UserPIIH\x00R\auserPii\x88\x01\x01\x12)\n" +
	"\x06status\x18\x03 \x01(\x0e2\x11.users.UserStatusR\x06status\x126\n" +
	"\bidp_type\x18\x04 \x01(\x0e2\x1b.users.IdentityProviderTypeR\aidpTypeB\v\n" +
	"\t_user_pii\"\xbf\x04\n" +
	"\aUserPII\x12\x1f\n" +
	"\busername\x18\x01 \x01(\tH\x00R\busername\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x02 \x01(\tH\x01R\x05email\x88\x01\x01\x12&\n" +
	"\fdisplay_name\x18\x03 \x01(\tH\x02R\vdisplayName\x88\x01\x01\x12\"\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tH\x03R\tfirstName\x88\x01\x01\x12 \n" +
	"\tlast_name\x18\x05 \x01(\tH\x04R\blastName\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x06 \x01(\tH\x05R\x05phone\x88\x01\x01\x12#\n" +
	"\n" +
	"department\x18\a \x01(\tH\x06R\n" +
	"department\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\b \x01(\tH\aR\x05title\x88\x01\x01\x12\"\n" +
	"\n" +
	"manager_id\x18\t \x01(\tH\bR\tmanagerId\x88\x01\x01\x12$\n" +
	"\vemployee_id\x18\n" +
	" \x01(\tH\tR\n" +
	"employeeId\x88\x01\x01\x12\x1f\n" +
	"\blocation\x18\v \x01(\tH\n" +
	"R\blocation\x88\x01\x01\x120\n" +
	"\n" +
	"attributes\x18\x14 \x03(\v2\x10.users.AttributeR\n" +
	"attributesB\v\n" +
	"\t_usernameB\b\n" +
	"\x06_emailB\x0f\n" +
	"\r_display_nameB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\b\n" +
	"\x06_phoneB\r\n" +
	"\v_departmentB\b\n" +
	"\x06_titleB\r\n" +
	"\v_manager_idB\x0e\n" +
	"\f_employee_idB\v\n" +
	"\t_location\"H\n" +
	"\tAttribute\x12%\n" +
	"\x03key\x18\x01 \x01(\x0e2\x13.users.AttributeKeyR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value*[\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ACTIVE\x10\x01\x12\x18\n" +
	"\x14USER_STATUS_DISABLED\x10\x02*-\n" +
	"\fAttributeKey\x12\x1d\n" +
	"\x19ATTRIBUTE_KEY_UNSPECIFIED\x10\x00*\x8c\x01\n" +
	"\x14IdentityProviderType\x12&\n" +
	"\"IDENTITY_PROVIDER_TYPE_UNSPECIFIED\x10\x00\x12+\n" +
	"'IDENTITY_PROVIDER_TYPE_ACTIVE_DIRECTORY\x10\x01\x12\x1f\n" +
	"\x1bIDENTITY_PROVIDER_TYPE_LDAP\x10\x022t\n" +
	"\fUsersService\x125\n" +
	"\tListUsers\x12\x17.users.ListUsersRequest\x1a\v.users.User\"\x000\x01\x12-\n" +
	"\aGetUser\x12\x15.users.GetUserRequest\x1a\v.users.UserB\bZ\x06pkg/pbb\x06proto3"

var (
	file_users_users_proto_rawDescOnce sync.Once
	file_users_users_proto_rawDescData []byte
)

func file_users_users_proto_rawDescGZIP() []byte {
	file_users_users_proto_rawDescOnce.Do(func() {
		file_users_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_users_proto_rawDesc), len(file_users_users_proto_rawDesc)))
	})
	return file_users_users_proto_rawDescData
}

var file_users_users_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_users_users_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_users_users_proto_goTypes = []any{
	(UserStatus)(0),           // 0: users.UserStatus
	(AttributeKey)(0),         // 1: users.AttributeKey
	(IdentityProviderType)(0), // 2: users.IdentityProviderType
	(*ListUsersRequest)(nil),  // 3: users.ListUsersRequest
	(*GetUserRequest)(nil),    // 4: users.GetUserRequest
	(*User)(nil),              // 5: users.User
	(*UserPII)(nil),           // 6: users.UserPII
	(*Attribute)(nil),         // 7: users.Attribute
}
var file_users_users_proto_depIdxs = []int32{
	6, // 0: users.User.user_pii:type_name -> users.UserPII
	0, // 1: users.User.status:type_name -> users.UserStatus
	2, // 2: users.User.idp_type:type_name -> users.IdentityProviderType
	7, // 3: users.UserPII.attributes:type_name -> users.Attribute
	1, // 4: users.Attribute.key:type_name -> users.AttributeKey
	3, // 5: users.UsersService.ListUsers:input_type -> users.ListUsersRequest
	4, // 6: users.UsersService.GetUser:input_type -> users.GetUserRequest
	5, // 7: users.UsersService.ListUsers:output_type -> users.User
	5, // 8: users.UsersService.GetUser:output_type -> users.User
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_users_users_proto_init() }
func file_users_users_proto_init() {
	if File_users_users_proto != nil {
		return
	}
	file_users_users_proto_msgTypes[2].OneofWrappers = []any{}
	file_users_users_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_users_proto_rawDesc), len(file_users_users_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_users_proto_goTypes,
		DependencyIndexes: file_users_users_proto_depIdxs,
		EnumInfos:         file_users_users_proto_enumTypes,
		MessageInfos:      file_users_users_proto_msgTypes,
	}.Build()
	File_users_users_proto = out.File
	file_users_users_proto_goTypes = nil
	file_users_users_proto_depIdxs = nil
}
